language: php
php:
  - '8.1'

before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install: composer install
script: $TRAVIS_BUILD_DIR/vendor/bin/phpunit --no-coverage
