language: minimal
dist: noble

before_install:
  - docker build --no-cache -t phalcon-abtest .
  - docker run --rm -v $(pwd):/app phalcon-abtest bash -c "composer install"
script: docker run --rm -v $(pwd):/app phalcon-abtest bash -c "vendor/bin/phpunit --no-coverage"
